version: '3.4'
services:
  minecraft:
    image: itzg/minecraft-bedrock-server
    container_name: minecraft-server
    environment:
      EULA: "TRUE"
      VERSION: "LATEST"
    ports:
      - 19132:19132/udp
    volumes:
      - ./server-provision-files:/data
    stdin_open: true
    tty: true